export const historia_clinica = {
  alergias: 'Ninguna',
  antecedentes_patologicos: 'Ninguno',
  antecedentes_quirurgicos: 'Ninguno',
  antecedentes_familiares: 'Ninguno',
  medicamentos_subministrados: 'Ninguno',
  gestas: '0',
  partos: '0',
  cesareas: '0',
  abortos: '0',
  metodo_anticonceptivo: 'Ninguno',
  habitos: 'Ninguno',
};
export const paciente = {
  tipo_de_sangre_id: '1',
  estado_civil_id: '1',
  nivel_de_instruccion_id: '1',
  etnia_id: '1',
  genero_id: '1',
  apellidos: 'Vivanco Mosquera',
  cedula: '123456',
  contacto_emergencia_nombre: 'Edgar',
  contacto_emergencia_telefono: '09212',
  direccion: 'Tumbaco',
  fechanacimiento: '07-27-1998',
  lugarnacimiento: 'Quito',
  nombres: 'Alejandro Manuel',
  numero_hijos: '0',
  ocupacion: 'Ingeniro de Software',
  telefono: '09232',
};
